services:
  nginx:
    image: nginx
    build: ./Blob-Client
    ports:
      - "443:443"
    networks:
      - srv
    restart: on-failure
    depends_on:
      - api
      - pong

  api:
    image: blob-api
    build: ./Blob-Api
    volumes:
      - db-data:/opt/blob-api/api/prisma
    secrets:
      - source: public_pem
        target: /opt/blob-api/api/public.pem
      - source: private_pem
        target: /opt/blob-api/api/private.pem
    networks:
      - srv
    expose:
      - "4000"
    restart: on-failure

  pong:
    image: blob-pong
    build: ./Blob-Pong
    networks:
      - srv
    expose:
      - "3000"
    restart: on-failure
  
  werewolf-server:
    image: werewolf-server
    build:
      context: ./Blob-Werewolf
      dockerfile: Dockerfile.server
    secrets:
      - source: public_pem
        target: /home/server/.config/unity3d/Blobox/Werewolf/public.pem
    networks:
      - srv
    expose:
      - "3044"
    restart: on-failure

  werewolf-client:
    image: werewolf-client
    build:
      context: ./Blob-Werewolf
      dockerfile: Dockerfile.web
    networks:
      - srv
    expose:
      - "3043"
    depends_on:
      - werewolf-server
    restart: on-failure

networks:
  srv:
    driver: bridge

secrets:
  public_pem:
    file: C:/Users/Matevos/Documents/public.pem
  private_pem:
    file: C:/Users/Matevos/Documents/private.pem

volumes:
  db-data: